Vagrant.configure("2") do |config|

    (1..4).each do |i|
    config.vm.define "rmq#{i}" do |vm|
    vm.vm.box = "generic/ubuntu2204"
    vm.vm.provider :libvirt do |domain|
      domain.cpus = 2
      domain.memory = 1024
    vm.vm.hostname = "rmq#{i}"
    end
  end
end

  config.vm.provision "file", source: "/etc/hosts", destination: "/tmp/hosts"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end
end
